USE `taipeiho_db`;

CREATE TABLE `request` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`type`	CHAR(1) DEFAULT NULL,
	`name`	VARCHAR(10) DEFAULT NULL,
	`sex`	TINYINT(1) DEFAULT NULL,
	`celphone`	VARCHAR(20)	DEFAULT NULL,
	`telephone`	VARCHAR(20)	DEFAULT NULL,
	`e-mail`	VARCHAR(255)	DEFAULT NULL,
	`comments`	VARCHAR(255)	DEFAULT NULL,
	PRIMARY KEY(`id`)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;
